# Generated by Django 5.0.1 on 2024-01-29 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_email', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.CharField(max_length=100)),
                ('grade_level', models.CharField(choices=[('7th-8th', '7th-8th Grade'), ('9th', '9th Grade'), ('10th', '10th Grade'), ('11th', '11th Grade'), ('12th', '12th Grade')], max_length=25)),
                ('school_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('programs_and_services', models.CharField(choices=[('college-packages', 'Applied'), ('strive', 'Interviews'), ('hourly', 'Rejected')], max_length=100)),
                ('date_appt', models.DateField()),
                ('how_can_we_help', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationDateRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('consultation_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eurekacac.consultationcontacts')),
            ],
        ),
    ]
