# Generated by Django 5.0.1 on 2024-01-29 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eurekacac', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsultationContacts',
            new_name='ConsultationContact',
        ),
    ]
